---
version: '3.3'
services:


  db:
    container_name: db
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"

  web:
    container_name: app
    build: ../welbexcar/
    restart: always
    command: >
      bash -c "python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn --bind 0:8000 welbexcar.wsgi"
    depends_on:
      - db
    env_file:
      - ./.env

  nginx:
    container_name: proxy
    image: nginx:1.23.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      # Данные, хранящиеся в томе media_value, будут доступны в контейнере web
      # через директорию /app/media/
    depends_on:
      - web
    restart: always

volumes:
  postgres_data:
  static_value:
  media_value: