# Generated by Django 3.2.19 on 2023-05-26 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0002_auto_20230526_1004'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Машина', 'verbose_name_plural': 'Машины'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
    ]
