# Generated by Django 3.2.19 on 2023-05-26 10:07

import cargo.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0003_auto_20230526_1211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'verbose_name': 'Груз', 'verbose_name_plural': 'Грузы'},
        ),
        migrations.AlterField(
            model_name='car',
            name='current_location',
            field=models.ForeignKey(default=cargo.models.Car.generate_unique_location, on_delete=django.db.models.deletion.CASCADE, related_name='current_location', to='cargo.location'),
        ),
    ]
